# Generated by Django 4.2 on 2025-09-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0003_suketcutiakademik'),
    ]

    operations = [
        migrations.AddField(
            model_name='skpembimbing',
            name='ttd_status',
            field=models.CharField(default='QRcode', max_length=20),
        ),
    ]
