# Generated by Django 4.2 on 2025-02-15 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jurusan', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('NonAktif', 'NonAktif')], default='Aktif', max_length=10)),
                ('kode_surat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LayananJenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_layanan', models.CharField(max_length=255)),
                ('prasyarat_layanan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strata', models.CharField(max_length=5)),
                ('nama_prodi', models.CharField(max_length=255)),
                ('gelar', models.CharField(max_length=10)),
                ('kode_mk', models.CharField(max_length=20)),
                ('nama_mk', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('NonAktif', 'NonAktif')], default='Aktif', max_length=10)),
                ('jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acd.jurusan')),
            ],
        ),
        migrations.CreateModel(
            name='UserProdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telp', models.CharField(max_length=15)),
                ('photo', models.FileField(blank=True, null=True, upload_to='static/img_profile/prodi/')),
                ('gender', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=15)),
                ('prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acd.prodi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMhs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telp', models.CharField(max_length=15)),
                ('photo', models.FileField(blank=True, null=True, upload_to='static/img_profile/mhs/')),
                ('gender', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=15)),
                ('prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acd.prodi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telp', models.CharField(max_length=15)),
                ('photo', models.FileField(blank=True, null=True, upload_to='static/img_profile/fakultas/')),
                ('gender', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telp', models.CharField(max_length=15)),
                ('photo', models.FileField(blank=True, null=True, upload_to='static/img_profile/dosen/')),
                ('gender', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=15)),
                ('prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acd.prodi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkripsiJudul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('judul_1', models.CharField(max_length=255, verbose_name='Judul 1')),
                ('deskripsi_judul_1', models.TextField(blank=True, null=True, verbose_name='Deskripsi Judul 1')),
                ('judul_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Judul 2')),
                ('deskripsi_judul_2', models.TextField(blank=True, null=True, verbose_name='Deskripsi Judul 2')),
                ('judul_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Judul 3')),
                ('deskripsi_judul_3', models.TextField(blank=True, null=True, verbose_name='Deskripsi Judul 3')),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Revision', 'Revision'), ('Approved', 'Approved')], default='Waiting', max_length=10)),
                ('status_ket', models.CharField(blank=True, max_length=255, null=True, verbose_name='status_ket')),
                ('penasehat_akademik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acd.prodi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skripsi_judul', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProdiPejabat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(choices=[('Ketua', 'Ketua'), ('Sekretaris', 'Sekretaris')], max_length=15)),
                ('tgl_mulai', models.DateField()),
                ('tgl_selesai', models.DateField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('plt', models.BooleanField(blank=True, null=True)),
                ('pejabat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acd.prodi')),
            ],
        ),
        migrations.CreateModel(
            name='NoSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(auto_now_add=True)),
                ('tahun', models.CharField(max_length=5)),
                ('nomor', models.IntegerField()),
                ('perihal', models.CharField(max_length=255)),
                ('tujuan', models.CharField(max_length=255)),
                ('adminp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminp_surat', to=settings.AUTH_USER_MODEL)),
                ('jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acd.jurusan')),
            ],
        ),
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('layanan_isi', models.TextField()),
                ('layanan_file', models.FileField(blank=True, null=True, upload_to='static/layanan_files/')),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Waiting', max_length=50)),
                ('hasil_test', models.TextField(blank=True, null=True)),
                ('hasil_file', models.FileField(blank=True, null=True, upload_to='static/layanan_hasil_files/')),
                ('hasil_link', models.URLField(blank=True, null=True)),
                ('adminp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layanan_adminp', to=settings.AUTH_USER_MODEL)),
                ('layanan_jenis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acd.layananjenis')),
                ('mhs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layanan_mhs', to=settings.AUTH_USER_MODEL)),
                ('prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acd.prodi')),
            ],
        ),
        migrations.CreateModel(
            name='JurusanPejabat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(choices=[('Ketua', 'Ketua'), ('Sekretaris', 'Sekretaris')], max_length=15)),
                ('tgl_mulai', models.DateField()),
                ('tgl_selesai', models.DateField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('plt', models.BooleanField(blank=True, null=True)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acd.jurusan')),
                ('pejabat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
