# Generated by Django 4.2 on 2025-01-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosurat',
            name='nomor',
            field=models.IntegerField(max_length=5),
        ),
    ]
