# Generated by Django 4.2 on 2025-05-18 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanan',
            name='mhs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acd.usermhs'),
        ),
    ]
