# Generated by Django 4.2 on 2025-02-22 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTDProdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(auto_now_add=True)),
                ('perihal', models.CharField(blank=True, max_length=255, null=True)),
                ('tujuan', models.CharField(blank=True, max_length=255, null=True)),
                ('ttd_jabatan', models.CharField(blank=True, max_length=255, null=True)),
                ('adminp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttdqr_admin', to=settings.AUTH_USER_MODEL)),
                ('prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acd.prodi')),
                ('ttd_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ttdqr_ttduser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
