# Generated by Django 4.2 on 2025-02-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdosen',
            old_name='prodi',
            new_name='prodis',
        ),
    ]
