# Generated by Django 4.2 on 2025-02-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermhs',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
