# Generated by Django 4.2 on 2025-09-17 10:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='skUjian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('nosurat', models.CharField(blank=True, max_length=50, null=True)),
                ('ttd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skujian_pejabatttd', to='acd.pejabat')),
                ('ujian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skujian_ujian', to='acd.ujian')),
            ],
        ),
    ]
