# Generated by Django 4.2 on 2025-09-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0002_skujian'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujian',
            name='status_ujian',
            field=models.CharField(choices=[('-', '-'), ('Pengajuan', 'Pengajuan'), ('Pembaharuan', 'Pembaharuan'), ('Terbit', 'Terbit')], default='-', max_length=15),
        ),
    ]
