# Generated by Django 4.2 on 2025-02-02 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acd', '0002_alter_nosurat_nomor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurusan',
            name='kajur',
        ),
        migrations.RemoveField(
            model_name='jurusan',
            name='kalab',
        ),
        migrations.RemoveField(
            model_name='jurusan',
            name='sekjur',
        ),
        migrations.CreateModel(
            name='JurusanPejabat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(choices=[('Ketua', 'Ketua'), ('Sekretaris', 'Sekretaris')], max_length=15)),
                ('tgl_mulai', models.DateField()),
                ('tgl_selesai', models.DateField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('plt', models.BooleanField(blank=True, null=True)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acd.jurusan')),
                ('pejabat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
