# Generated by Django 4.2 on 2025-02-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0002_rename_prodi_userdosen_prodis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdosen',
            old_name='prodis',
            new_name='prodi',
        ),
    ]
