# Generated by Django 4.2 on 2025-02-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0002_usermhs_tempat_lahir'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermhs',
            name='tgl_lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
