# Generated by Django 4.2 on 2025-08-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0002_proposal_ksm'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='lembar_pengesahan',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syaratproposal/'),
        ),
    ]
