# Generated by Django 4.2 on 2025-02-02 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acd', '0003_remove_jurusan_kajur_remove_jurusan_kalab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodi',
            name='kaprodi',
        ),
        migrations.RemoveField(
            model_name='prodi',
            name='sekprodi',
        ),
        migrations.CreateModel(
            name='ProdiPejabat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(choices=[('Ketua', 'Ketua'), ('Sekretaris', 'Sekretaris')], max_length=15)),
                ('tgl_mulai', models.DateField()),
                ('tgl_selesai', models.DateField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('plt', models.BooleanField(blank=True, null=True)),
                ('pejabat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acd.prodi')),
            ],
        ),
    ]
