# Generated by Django 4.2 on 2025-02-23 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acd', '0003_rename_prodis_userdosen_prodi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skripsijudul',
            name='user',
        ),
        migrations.AddField(
            model_name='skripsijudul',
            name='mhs',
            field=models.ForeignKey(default='mhs001', on_delete=django.db.models.deletion.CASCADE, related_name='skripsi_judul', to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
    ]
