# Generated by Django 4.2 on 2025-09-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0003_ujian_status_ujian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ujian',
            name='status_ujian',
            field=models.CharField(choices=[('-', '-'), ('Usulan', 'Usulan'), ('Pengajuan', 'Pengajuan'), ('Pembaharuan', 'Pembaharuan'), ('Terbit', 'Terbit')], default='-', max_length=15),
        ),
    ]
