# Generated by Django 4.2 on 2025-02-15 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acd', '0003_usermhs_tgl_lahir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skripsijudul',
            name='penasehat_akademik',
        ),
        migrations.AddField(
            model_name='usermhs',
            name='penasehat_akademik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermhs_pa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermhs',
            name='prodi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermhs_prodi', to='acd.prodi'),
        ),
    ]
