# Generated by Django 4.2 on 2025-08-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0003_proposal_lembar_pengesahan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='rek_koran',
            new_name='konsultasi_skripsi',
        ),
    ]
