# Generated by Django 4.2 on 2025-05-18 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0003_alter_layanan_mhs'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanan',
            name='mhs2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layanan_mhs2', to='acd.usermhs'),
        ),
    ]
