# Generated by Django 4.2 on 2025-02-23 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acd', '0004_remove_skripsijudul_user_skripsijudul_mhs'),
    ]

    operations = [
        migrations.AddField(
            model_name='skripsijudul',
            name='judul',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skripsijudul',
            name='pembimbing1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skripsi_pbb1', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='skripsijudul',
            name='pembimbing2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skripsi_pbb2', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
