# Generated by Django 4.2 on 2025-08-25 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0004_rename_rek_koran_proposal_konsultasi_skripsi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='persetujuan_proposal',
        ),
    ]
