# Generated by Django 4.2 on 2025-09-13 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acd', '0004_skpembimbing_ttd_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skpenguji',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='ujian',
            name='rekomendasi_akademik',
        ),
        migrations.AddField(
            model_name='skpenguji',
            name='ttd_status',
            field=models.CharField(default='QRcode', max_length=20),
        ),
        migrations.AddField(
            model_name='ujian',
            name='bebas_pustaka_univ',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syaratujian/'),
        ),
        migrations.AddField(
            model_name='ujian',
            name='foto_latar_biru',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syaratujian/'),
        ),
        migrations.AddField(
            model_name='ujian',
            name='ktp',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syaratujian/'),
        ),
        migrations.AddField(
            model_name='ujian',
            name='matriks_perbaikan',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syaratujian/'),
        ),
        migrations.AddField(
            model_name='ujian',
            name='persetujuan_waktu',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syaratujian/'),
        ),
        migrations.AddField(
            model_name='ujian',
            name='ukt_terakhir',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syaratujian/'),
        ),
        migrations.AddField(
            model_name='ujian',
            name='usulan_baak',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syaratujian/'),
        ),
        migrations.AlterField(
            model_name='pejabat',
            name='jabatan',
            field=models.CharField(choices=[('Dekan', 'Dekan'), ('Wakil Dekan I', 'Wakil Dekan I'), ('Wakil Dekan II', 'Wakil Dekan II'), ('Wakil Dekan III', 'Wakil Dekan III'), ('Wakil Dekan IV', 'Wakil Dekan IV'), ('Penjaminan Mutu', 'Penjaminan Mutu'), ('Kepala Bagian Umum', 'Kepala Bagian Umum'), ('Ketua Jurusan', 'Ketua Jurusan'), ('Sekretaris Jurusan', 'Sekretaris Jurusan'), ('Ketua Prodi', 'Ketua Prodi'), ('Sekretaris Prodi', 'Sekretaris Prodi'), ('Pustakawan', 'Pustakawan')], max_length=30),
        ),
        migrations.CreateModel(
            name='SuketUsulanUjianSkripsi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('no_surat', models.CharField(blank=True, max_length=50, null=True)),
                ('usul_tgl', models.DateField(blank=True, null=True)),
                ('usul_jam', models.TimeField(blank=True, null=True)),
                ('usul_tempat', models.CharField(max_length=255)),
                ('ttd_status', models.CharField(default='QRcode', max_length=20)),
                ('adminp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_admin', to=settings.AUTH_USER_MODEL)),
                ('ketua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_ketua', to='acd.pejabat')),
                ('mhs_judul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_mhs_judul', to='acd.skripsijudul')),
                ('penguji1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_pgj1', to='acd.userdosen')),
                ('penguji2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_pgj2', to='acd.userdosen')),
                ('sekretaris', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_sekretaris', to='acd.userdosen')),
                ('ttd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_ttd', to='acd.pejabat')),
                ('wakil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_wakil', to='acd.pejabat')),
            ],
        ),
        migrations.CreateModel(
            name='SuketBebasPustaka',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('no_surat', models.CharField(blank=True, max_length=50, null=True)),
                ('ttd_status', models.CharField(default='QRcode', max_length=20)),
                ('adminp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spb_admin', to=settings.AUTH_USER_MODEL)),
                ('mhs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spb_mhs', to='acd.usermhs')),
                ('ttd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spb_ttd', to='acd.pejabat')),
            ],
        ),
        migrations.AddField(
            model_name='skpenguji',
            name='usulan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skpgj_usulan', to='acd.suketusulanujianskripsi'),
        ),
    ]
