# Generated by Django 4.2 on 2025-02-20 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acd', '0004_remove_skripsijudul_penasehat_akademik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TtdProdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField(auto_now_add=True)),
                ('perihal', models.CharField(max_length=255)),
                ('tujuan', models.CharField(max_length=255)),
                ('adminp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttdqr_admin', to=settings.AUTH_USER_MODEL)),
                ('pejabat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acd.prodipejabat')),
                ('prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acd.prodi')),
            ],
        ),
    ]
