# Generated by Django 4.2 on 2025-08-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0005_remove_proposal_persetujuan_proposal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='lembar_pengesahan',
            new_name='persetujuan_proposal',
        ),
    ]
