# Generated by Django 4.2 on 2025-09-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0005_alter_ujian_status_ujian'),
    ]

    operations = [
        migrations.DeleteModel(
            name='skPenguji',
        ),
    ]
