# Generated by Django 4.2 on 2025-02-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0005_skripsijudul_judul_skripsijudul_pembimbing1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skripsijudul',
            name='status_sk',
            field=models.CharField(choices=[('-', '-'), ('Pengajuan', 'Pengajuan'), ('Pembaharuan', 'Pembaharuan'), ('Terbit', 'Terbit')], default='-', max_length=15),
        ),
    ]
