# Generated by Django 4.2 on 2025-09-19 00:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0005_remove_skpenguji_proposal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='skUjian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('nosurat', models.CharField(blank=True, max_length=50, null=True)),
                ('ttd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skujian_pejabatttd', to='acd.pejabat')),
            ],
        ),
        migrations.AddField(
            model_name='ujian',
            name='sekretaris',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ujian_sekretaris', to='acd.userdosen'),
        ),
        migrations.AddField(
            model_name='ujian',
            name='status_ujian',
            field=models.CharField(choices=[('-', '-'), ('Usulan', 'Usulan'), ('Pengajuan', 'Pengajuan'), ('Terbit', 'Terbit')], default='-', max_length=15),
        ),
        migrations.DeleteModel(
            name='skPenguji',
        ),
        migrations.AddField(
            model_name='skujian',
            name='ujian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skujian_ujian', to='acd.ujian'),
        ),
    ]
