# Generated by Django 4.2 on 2026-01-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0006_skujian_ujian_sekretaris_ujian_status_ujian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skripsijudul',
            name='kajur_persetujuan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
