# Generated by Django 4.2 on 2025-08-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0006_rename_lembar_pengesahan_proposal_persetujuan_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasil',
            name='buku_konsultasi',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syarathasil/'),
        ),
        migrations.AddField(
            model_name='hasil',
            name='kartu_kontrol_seminar',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syarathasil/'),
        ),
        migrations.AddField(
            model_name='hasil',
            name='krs',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syarathasil/'),
        ),
        migrations.AddField(
            model_name='hasil',
            name='ksm',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syarathasil/'),
        ),
        migrations.AddField(
            model_name='hasil',
            name='persetujuan_hasil',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syarathasil/'),
        ),
        migrations.AddField(
            model_name='hasil',
            name='suket_selesai_meneliti',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syarathasil/'),
        ),
        migrations.AddField(
            model_name='hasil',
            name='transkrip',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syarathasil/'),
        ),
    ]
