# Generated by Django 4.2 on 2026-01-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0007_skripsijudul_kajur_persetujuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='skripsijudul',
            name='kajur_komentar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
