# Generated by Django 4.2 on 2025-09-01 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acd', '0007_hasil_buku_konsultasi_hasil_kartu_kontrol_seminar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuketBerkelakuanBaik',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('no_surat', models.CharField(blank=True, max_length=50, null=True)),
                ('perihal', models.CharField(blank=True, max_length=255, null=True)),
                ('tahun_akademik', models.CharField(blank=True, max_length=20, null=True)),
                ('ttd_status', models.CharField(default='QRcode', max_length=20)),
                ('adminp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skb_admin', to=settings.AUTH_USER_MODEL)),
                ('mhs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skb_mhs', to='acd.usermhs')),
                ('ttd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skb_ttd', to='acd.pejabat')),
            ],
        ),
    ]
