# Generated by Django 4.2 on 2025-06-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0007_remove_layanan_mhs2_alter_layanan_mhs'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermhs',
            name='alamat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
