# Generated by Django 4.2 on 2026-01-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0008_skripsijudul_kajur_komentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='skripsijudul',
            name='kaprodi_komentar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skripsijudul',
            name='kaprodi_persetujuan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
