# Generated by Django 4.2 on 2025-09-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0008_suketberkelakuanbaik'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuketBerkelakuanBaik',
        ),
    ]
