# Generated by Django 4.2 on 2026-02-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0009_skripsijudul_kaprodi_komentar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasil',
            name='date_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
