# Generated by Django 4.2 on 2026-02-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0010_alter_hasil_date_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasil',
            name='date_in',
            field=models.DateField(blank=True, null=True),
        ),
    ]
