# Generated by Django 4.2 on 2025-09-01 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acd', '0011_cutiakademik'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuketCutiAkademik',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('no_surat', models.CharField(blank=True, max_length=50, null=True)),
                ('alasan', models.CharField(blank=True, max_length=100, null=True)),
                ('terakhir_terdaftar', models.CharField(blank=True, max_length=20, null=True)),
                ('cuti_semester', models.CharField(blank=True, max_length=20, null=True)),
                ('terhitung_cuti', models.CharField(blank=True, max_length=50, null=True)),
                ('tahun_akademik', models.CharField(blank=True, max_length=20, null=True)),
                ('kembali_aktif', models.CharField(blank=True, max_length=50, null=True)),
                ('ttd_status', models.CharField(default='QRcode', max_length=20)),
                ('adminp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scak_admin', to=settings.AUTH_USER_MODEL)),
                ('mhs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scak_mhs', to='acd.usermhs')),
                ('ttd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scak_ttd', to='acd.pejabat')),
            ],
        ),
        migrations.DeleteModel(
            name='CutiAkademik',
        ),
    ]
