# Generated by Django 4.2 on 2025-09-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0012_suketcutiakademik_delete_cutiakademik'),
    ]

    operations = [
        migrations.AddField(
            model_name='skpembimbing',
            name='ttd_status',
            field=models.CharField(default='QRcode', max_length=20),
        ),
    ]
