# Generated by Django 4.2 on 2025-09-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0013_skpembimbing_ttd_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujian',
            name='ukt_terakhir',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syaratujian/'),
        ),
    ]
