# Generated by Django 4.2 on 2025-09-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0014_ujian_ukt_terakhir'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujian',
            name='bebas_pustaka_univ',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syaratujian/'),
        ),
    ]
