# Generated by Django 4.2 on 2025-09-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0016_suketbebaspustaka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pejabat',
            name='jabatan',
            field=models.CharField(choices=[('Dekan', 'Dekan'), ('Wakil Dekan I', 'Wakil Dekan I'), ('Wakil Dekan II', 'Wakil Dekan II'), ('Wakil Dekan III', 'Wakil Dekan III'), ('Wakil Dekan IV', 'Wakil Dekan IV'), ('Penjaminan Mutu', 'Penjaminan Mutu'), ('Kepala Bagian Umum', 'Kepala Bagian Umum'), ('Ketua Jurusan', 'Ketua Jurusan'), ('Sekretaris Jurusan', 'Sekretaris Jurusan'), ('Ketua Prodi', 'Ketua Prodi'), ('Sekretaris Prodi', 'Sekretaris Prodi'), ('Pustakawan', 'Pustakawan')], max_length=30),
        ),
    ]
