# Generated by Django 4.2 on 2025-09-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0017_alter_pejabat_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujian',
            name='ktp',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syaratujian/'),
        ),
        migrations.AddField(
            model_name='ujian',
            name='matriks_perbaikan',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syaratujian/'),
        ),
        migrations.AddField(
            model_name='ujian',
            name='usulan_baak',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syaratujian/'),
        ),
    ]
