# Generated by Django 4.2 on 2025-09-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0018_ujian_ktp_ujian_matriks_perbaikan_ujian_usulan_baak'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujian',
            name='persetujuan_waktu',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syaratujian/'),
        ),
    ]
