# Generated by Django 4.2 on 2025-09-05 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acd', '0019_ujian_persetujuan_waktu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuketUsulanUjianSkripsi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('no_surat', models.CharField(blank=True, max_length=50, null=True)),
                ('usul_tgl', models.DateField(blank=True, null=True)),
                ('usul_jam', models.TimeField(blank=True, null=True)),
                ('usul_tempat', models.CharField(max_length=255)),
                ('adminp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_admin', to=settings.AUTH_USER_MODEL)),
                ('ketua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_ketua', to='acd.pejabat')),
                ('mhs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_mhs', to='acd.usermhs')),
                ('pembimbing1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_pbb1', to='acd.userdosen')),
                ('pembimbing2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_pbb2', to='acd.userdosen')),
                ('penguji1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_pgj1', to='acd.userdosen')),
                ('penguji2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_pgj2', to='acd.userdosen')),
                ('sekretaris', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_sekretaris', to='acd.userdosen')),
                ('wakil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_wakil', to='acd.pejabat')),
            ],
        ),
    ]
