# Generated by Django 4.2 on 2025-09-05 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0020_suketusulanujianskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='suketusulanujianskripsi',
            name='ttd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_ttd', to='acd.pejabat'),
        ),
        migrations.AddField(
            model_name='suketusulanujianskripsi',
            name='ttd_status',
            field=models.CharField(default='QRcode', max_length=20),
        ),
    ]
