# Generated by Django 4.2 on 2025-09-06 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0021_suketusulanujianskripsi_ttd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suketusulanujianskripsi',
            name='pembimbing1',
        ),
        migrations.RemoveField(
            model_name='suketusulanujianskripsi',
            name='pembimbing2',
        ),
        migrations.RemoveField(
            model_name='suketusulanujianskripsi',
            name='penguji1',
        ),
        migrations.RemoveField(
            model_name='suketusulanujianskripsi',
            name='penguji2',
        ),
    ]
