# Generated by Django 4.2 on 2025-09-06 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0022_remove_suketusulanujianskripsi_pembimbing1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suketusulanujianskripsi',
            name='pembimbing1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_pbb1', to='acd.userdosen'),
        ),
        migrations.AddField(
            model_name='suketusulanujianskripsi',
            name='pembimbing2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_pbb2', to='acd.userdosen'),
        ),
        migrations.AddField(
            model_name='suketusulanujianskripsi',
            name='penguji1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_pgj1', to='acd.userdosen'),
        ),
        migrations.AddField(
            model_name='suketusulanujianskripsi',
            name='penguji2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_pgj2', to='acd.userdosen'),
        ),
    ]
