# Generated by Django 4.2 on 2025-09-06 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0023_suketusulanujianskripsi_pembimbing1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suketusulanujianskripsi',
            name='mhs_judul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='susk_mhs_judul', to='acd.skripsijudul'),
        ),
    ]
