# Generated by Django 4.2 on 2025-09-06 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0024_suketusulanujianskripsi_mhs_judul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suketusulanujianskripsi',
            name='mhs',
        ),
    ]
