# Generated by Django 4.2 on 2025-09-06 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0025_remove_suketusulanujianskripsi_mhs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ujian',
            name='rekomendasi_akademik',
        ),
    ]
