# Generated by Django 4.2 on 2025-09-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0026_remove_ujian_rekomendasi_akademik'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujian',
            name='foto_latar_biru',
            field=models.FileField(blank=True, null=True, upload_to='layanan/syaratujian/'),
        ),
    ]
