# Generated by Django 4.2 on 2025-09-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0027_ujian_foto_latar_biru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suketusulanujianskripsi',
            name='pembimbing1',
        ),
        migrations.RemoveField(
            model_name='suketusulanujianskripsi',
            name='pembimbing2',
        ),
    ]
