# Generated by Django 4.2 on 2025-09-07 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0028_remove_suketusulanujianskripsi_pembimbing1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skpenguji',
            name='proposal',
        ),
        migrations.AddField(
            model_name='skpenguji',
            name='usulan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skpgj_usulan', to='acd.suketusulanujianskripsi'),
        ),
    ]
