# Generated by Django 4.2 on 2025-09-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0029_remove_skpenguji_proposal_skpenguji_usulan'),
    ]

    operations = [
        migrations.AddField(
            model_name='skpenguji',
            name='ttd_status',
            field=models.CharField(default='QRcode', max_length=20),
        ),
    ]
